# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dbccb9aacd6253a8efed93b16c70def15945468affd824ca32066401275b9058963dac763f491e56feae5f77112f79ed19cb2280ccb79ea7fb686373f740682

test:
  secret_key_base: ccb4a4870b3d95c12e586707e970e07d8ddd9a6bfd1df4c738aa79dc60780a3c16928923b9186ab1a52b4077928d875e24302d2ff2b3e59db6543ed6152d9637

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
